sudo: required

services:
 - docker 

before_install:
  - docker build -t anilkris/docker-react -f Dockerfile.Dev .

script:
  - docker run anilkris/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" 
  app: "docker"
  env : "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-013847779196"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
